// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvUn4dAdfAh61Nk8qoIc9ubgHtKFF8L4E',
    appId: '1:784534102255:web:f87fec422404f01bed7b1a',
    messagingSenderId: '784534102255',
    projectId: 'gr05-docubox-2025-inters-1af0a',
    authDomain: 'gr05-docubox-2025-inters-1af0a.firebaseapp.com',
    storageBucket: 'gr05-docubox-2025-inters-1af0a.firebasestorage.app',
    measurementId: 'G-JB37KC0HY8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIM3gCz5tk4cab1h4BG2SyNyWmfmPk2xI',
    appId: '1:784534102255:android:90b7e8885f19ba20ed7b1a',
    messagingSenderId: '784534102255',
    projectId: 'gr05-docubox-2025-inters-1af0a',
    storageBucket: 'gr05-docubox-2025-inters-1af0a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9jrnq17zoMhepMl7lTjrym1cOorQRfbw',
    appId: '1:784534102255:ios:ff6dea5198fb6fb7ed7b1a',
    messagingSenderId: '784534102255',
    projectId: 'gr05-docubox-2025-inters-1af0a',
    storageBucket: 'gr05-docubox-2025-inters-1af0a.firebasestorage.app',
    iosClientId: '784534102255-00e1de3emqnqugmenil0b97ub329aq8f.apps.googleusercontent.com',
    iosBundleId: 'com.example.docuboxProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9jrnq17zoMhepMl7lTjrym1cOorQRfbw',
    appId: '1:784534102255:ios:ff6dea5198fb6fb7ed7b1a',
    messagingSenderId: '784534102255',
    projectId: 'gr05-docubox-2025-inters-1af0a',
    storageBucket: 'gr05-docubox-2025-inters-1af0a.firebasestorage.app',
    iosClientId: '784534102255-00e1de3emqnqugmenil0b97ub329aq8f.apps.googleusercontent.com',
    iosBundleId: 'com.example.docuboxProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvUn4dAdfAh61Nk8qoIc9ubgHtKFF8L4E',
    appId: '1:784534102255:web:d59ff6f73c84ae28ed7b1a',
    messagingSenderId: '784534102255',
    projectId: 'gr05-docubox-2025-inters-1af0a',
    authDomain: 'gr05-docubox-2025-inters-1af0a.firebaseapp.com',
    storageBucket: 'gr05-docubox-2025-inters-1af0a.firebasestorage.app',
    measurementId: 'G-YLKXSVGJ52',
  );
}
